// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:877893213406:web:8c0d1d4ff76139295af64f',
    messagingSenderId: '877893213406',
    projectId: 'tecnicos-inseel-sas',
    authDomain: 'tecnicos-inseel-sas.firebaseapp.com',
    storageBucket: 'tecnicos-inseel-sas.firebasestorage.app',
    measurementId: 'G-8LWKQ2JR56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:877893213406:android:6575293fd6549b235af64f',
    messagingSenderId: '877893213406',
    projectId: 'tecnicos-inseel-sas',
    storageBucket: 'tecnicos-inseel-sas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:877893213406:ios:adb161cb6ece70415af64f',
    messagingSenderId: '877893213406',
    projectId: 'tecnicos-inseel-sas',
    storageBucket: 'tecnicos-inseel-sas.firebasestorage.app',
    iosBundleId: 'com.example.tecnicosInseel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:877893213406:ios:adb161cb6ece70415af64f',
    messagingSenderId: '877893213406',
    projectId: 'tecnicos-inseel-sas',
    storageBucket: 'tecnicos-inseel-sas.firebasestorage.app',
    iosBundleId: 'com.example.tecnicosInseel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:877893213406:web:f0f7e6693b8edb2d5af64f',
    messagingSenderId: '877893213406',
    projectId: 'tecnicos-inseel-sas',
    authDomain: 'tecnicos-inseel-sas.firebaseapp.com',
    storageBucket: 'tecnicos-inseel-sas.firebasestorage.app',
    measurementId: 'G-HHL5P906T0',
  );
}
